version: '3'
services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    env_file:
      - variablesClient.env

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - 3100:3100
    env_file:
      - variablesServer.env
    