export { ReactComponent as SearchIcon } from './search.svg';
export { ReactComponent as PersonIcon } from './person.svg';
export { ReactComponent as CartIcon } from './cart.svg';
export { ReactComponent as FavoriteIcon } from './favorite.svg';
export { ReactComponent as DarkModeIcon } from './darkMode.svg';
export { ReactComponent as LightModeIcon } from './lightMode.svg';
export { ReactComponent as DotsIcon } from './dots.svg';
export { ReactComponent as HomeIcon } from './home.svg';
export { ReactComponent as MenuIcon } from './menu.svg';
